export { default as SuperAdminDashboard } from './pages/SuperAdminDashboard'
export { default as UniversitiesPage } from './pages/UniversitiesPage'
export { default as UsersPage } from './pages/UsersPage'
export { default as ApprovalsPage } from './pages/ApprovalsPage'
export { default as AnalyticsPage } from './pages/AnalyticsPage'
export { default as SettingsPage } from './pages/SettingsPage'
export { default as QuestionsPage } from './pages/QuestionsPage'
export { SuperAdminService } from './services/superAdminService'
export { useSuperAdminStats } from './hooks/useSuperAdminStats'
export { useUserApprovals } from './hooks/useUserApprovals'